name = "problem011"
version = "0.1.0"
license = "license"
author = "Thomas Hoek"
copyright = "Copyright 2022, Thomas Hoek"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
